np_music = ["Rock star", "Dance Monkey", "Roses"]
print(np_music)
np_music.append("Own It")
print(np_music)
np_music.pop(1)
print(np_music)
mp_music = ["Lonely", "The Box", "Rover"]
np_music.extend(mp_music)
print(np_music)
np_music.remove("Roses")
print(np_music)
np_music.pop(1)
print(np_music)
np_music.sort()
print(np_music)
np_music.sort(reverse = True)
print(np_music)
np_music.reverse()
print(np_music)